### ISSUE TITLE
BioGRID

### ISSUE THREAD

**Issue by sophiakrix** [bio2bel/bio2bel#31]
Mapping from BioGRID interaction types to BEL

**Comment by sophiakrix** [comment]
Similarly as to IntAct, I am retrieving the file for BioGRID via an intermediate database. Should I change this to retrieve the file directly from the BioGRID website?

**Comment by sophiakrix** [comment]
- [ ] download data

- [ ] understand headers

- [ ] add triples to BEL graph

**Comment by sophiakrix** [comment]
For BioGRID, as well as for IntAct, I get the same error when I try read_csv with the file downloaded by ensure_path:

  File "/anaconda3/envs/bio2bel_intact/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Here is the link to the file:
https://github.com/sophiakrix/bio2bel/blob/master/src/bio2bel/sources/biogrid.py

**Comment by cthoyt** [comment]
First thing to do is to look at the data yourself. you'll notice that this is actually an HTML page - it seems that the BioGRID is adverse to people downloading their data. So you have to go a bit deeper and figure out exactly how the information gets to your computer.

1. open the download page at https://downloads.thebiogrid.org/File/BioGRID/Release-Archive/BIOGRID-3.5.183/BIOGRID-ALL-3.5.183.mitab.zip
2. If you copy the link, you'll just redirect to the page you're on, since the download is initiated by javascript. therefore you have to deconstruct the javascript of the page to figure out the file location. Alternatively, you can use the network monitor in a modern browser to figure out any URLs that are requested. I figured out that the actual file's URL is at https://downloads.thebiogrid.org/Download/BioGRID/Release-Archive/BIOGRID-3.5.183/BIOGRID-ALL-3.5.183.mitab.zip. I updated the download link in 1f981f0 for you

**Comment by sophiakrix** [comment]
Oh, that explains a lot. How exactly did you make use of the network monitor?

Thanks a lot!

**Comment by cthoyt** [comment]
https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor

**Comment by sophiakrix** [comment]
Great, thanks!
