### ISSUE TITLE
Pin sqlalchemy version?

### ISSUE THREAD

**Issue by ddomingof** [bio2bel/bio2bel#7]

**Comment by cthoyt** [comment]
The new version of pip seems to be a little less interested in the order of priority. Before, bio2bel did not pin a version of sqlalchemy since it usually installs pybel first. However, we can probably just remove the pinned version of sqlalchemy from pybel and still be fine. I just haven't done this because i'm not willing to risk anything breaking on BEL Commons because of it.

The real solution is that development forwards for pybel will continue in the tuplectomy (0.12.x) and the BEL Commons (0.11.x) will get bug fixes ported backwards.

**Comment by cthoyt** [comment]
Won't pin version of SQLAlchemy - seems like everything is working now on both sides
